name: Keep Backend Alive

on:
  schedule:
    - cron: '0-59/5 * * * *'  # at 0,5,10,...
    - cron: '1-59/5 * * * *'  # at 1,6,11,...
    - cron: '2-59/5 * * * *'
    - cron: '3-59/5 * * * *'
    - cron: '4-59/5 * * * *'
  workflow_dispatch:

jobs:
  ping-backend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: pip install requests
        
      - name: Run keep-alive script
        run: python main.py # or whatever your python file name is
